'use client';

import { useState, useRef } from 'react';
import { LearningPath, Milestone } from '@/app/actions/learning-path';
import { MilestoneCard } from '@/components/learning-path/MilestoneCard';
import { toPng } from 'html-to-image';
import jsPDF from 'jspdf';

interface RoadmapVisualizationProps {
    learningPath: LearningPath;
    onReset: () => void;
}

export function RoadmapVisualization({ learningPath, onReset }: RoadmapVisualizationProps) {
    const [expandedMilestone, setExpandedMilestone] = useState<number | null>(null);
    const roadmapRef = useRef<HTMLDivElement>(null);
    const [isExporting, setIsExporting] = useState(false);

    const toggleMilestone = (id: number) => {
        setExpandedMilestone(expandedMilestone === id ? null : id);
    };

    const handleDownloadPDF = () => {
        setIsExporting(true);

        try {
            const doc = new jsPDF();
            const pageWidth = doc.internal.pageSize.getWidth();
            const pageHeight = doc.internal.pageSize.getHeight();
            let y = 20;

            // Safe text helper (strips emojis to prevent font errors)
            const cleanText = (str: string) => {
                return str.replace(/[\u{1F600}-\u{1F64F}\u{1F300}-\u{1F5FF}\u{1F680}-\u{1F6FF}\u{1F1E0}-\u{1F1FF}\u{2600}-\u{26FF}\u{2700}-\u{27BF}]/gu, '').trim();
            };

            const footer = (pageNum: number) => {
                doc.setFont('helvetica', 'italic');
                doc.setFontSize(8);
                doc.setTextColor(150);
                doc.text(`Page ${pageNum} - Generated by 2050 Roadmap AI`, pageWidth - 20, pageHeight - 10, { align: 'right' });
            };

            const checkPageBreak = (heightNeeded: number) => {
                if (y + heightNeeded > pageHeight - 20) {
                    footer(doc.getNumberOfPages());
                    doc.addPage();
                    y = 20;
                }
            };

            // --- Header ---
            doc.setFillColor(16, 22, 47); // Brand Dark Blue
            doc.rect(0, 0, pageWidth, 40, 'F');

            doc.setFont('helvetica', 'bold');
            doc.setFontSize(24);
            doc.setTextColor(255, 255, 255);
            doc.text("Learning Roadmap", 20, 20);

            doc.setFontSize(10);
            doc.setTextColor(255, 211, 0); // Accent Yellow
            doc.text("GENERATED BY 2050 Developer", 20, 30);

            y = 55;

            // --- Role Title ---
            doc.setFont('helvetica', 'bold');
            doc.setFontSize(18);
            doc.setTextColor(16, 22, 47);
            const title = cleanText(learningPath.title);
            const titleSplit = doc.splitTextToSize(title, pageWidth - 40);
            doc.text(titleSplit, 20, y);
            y += (titleSplit.length * 8) + 10;

            // Description
            doc.setFont('helvetica', 'normal');
            doc.setFontSize(10);
            doc.setTextColor(80);
            const desc = cleanText(learningPath.description);
            const descSplit = doc.splitTextToSize(desc, pageWidth - 40);
            doc.text(descSplit, 20, y);
            y += (descSplit.length * 5) + 15;

            // Stats Grid
            doc.setDrawColor(230);
            doc.line(20, y, pageWidth - 20, y);
            y += 15;

            doc.setFont('helvetica', 'bold');
            doc.setFontSize(10);
            doc.setTextColor(50);
            doc.text(`DURATION: ${cleanText(learningPath.estimatedDuration)}`, 20, y);
            doc.text(`MILESTONES: ${learningPath.milestones.length}`, 80, y);
            doc.text(`RESOURCES: ${learningPath.milestones.reduce((sum, m) => sum + m.resources.length, 0)}`, 140, y);
            y += 5;

            doc.line(20, y, pageWidth - 20, y);
            y += 20;

            // --- Milestones ---
            learningPath.milestones.forEach((milestone, index) => {
                checkPageBreak(50);

                // Milestone Badge
                doc.setFillColor(255, 211, 0); // Yellow
                doc.circle(24, y - 4, 3, 'F');
                doc.setDrawColor(255, 211, 0);
                // Vertical connecting line
                doc.line(24, y - 4, 24, y + 40);

                doc.setFont('helvetica', 'bold');
                doc.setFontSize(12);
                doc.setTextColor(0);

                const mTitle = `${index + 1}. ${cleanText(milestone.title)}`;
                doc.text(mTitle, 35, y);

                doc.setFont('helvetica', 'normal');
                doc.setFontSize(9);
                doc.setTextColor(100);
                doc.text(cleanText(milestone.duration), pageWidth - 20, y, { align: 'right' });
                y += 8;

                // Description
                const mDesc = cleanText(milestone.description);
                const mDescSplit = doc.splitTextToSize(mDesc, pageWidth - 60);
                checkPageBreak(mDescSplit.length * 4);
                doc.setTextColor(80);
                doc.text(mDescSplit, 35, y);
                y += (mDescSplit.length * 4) + 8;

                // Tasks
                if (milestone.tasks.length > 0) {
                    checkPageBreak(20);
                    doc.setFont('helvetica', 'bold');
                    doc.setFontSize(9);
                    doc.setTextColor(0);
                    doc.text("Key Tasks:", 35, y);
                    y += 5;

                    doc.setFont('helvetica', 'normal');
                    milestone.tasks.forEach(task => {
                        const tText = `- ${cleanText(task)}`;
                        const tSplit = doc.splitTextToSize(tText, pageWidth - 65);
                        checkPageBreak(tSplit.length * 4);
                        doc.text(tSplit, 40, y);
                        y += (tSplit.length * 4) + 2;
                    });
                    y += 5;
                }

                // Resources
                if (milestone.resources.length > 0) {
                    checkPageBreak(20);
                    doc.setFont('helvetica', 'bold');
                    doc.setFontSize(9);
                    doc.setTextColor(0);
                    doc.text("Resources:", 35, y);
                    y += 5;

                    milestone.resources.forEach(res => {
                        const rTitle = `[${res.type.toUpperCase()}] ${cleanText(res.title)}`;
                        checkPageBreak(10);
                        doc.setTextColor(37, 99, 235); // Link Blue
                        doc.textWithLink(rTitle, 40, y, { url: res.url });
                        y += 5;
                    });
                }

                y += 15;
            });

            footer(doc.getNumberOfPages());
            doc.save(`2050-roadmap-${cleanText(learningPath.title).slice(0, 30).replace(/\s+/g, '-')}.pdf`);

        } catch (error) {
            console.error('Error generating PDF:', error);
            alert('Failed to generate PDF. Please try again.');
        } finally {
            setIsExporting(false);
        }
    };

    return (
        <div className="max-w-6xl mx-auto" ref={roadmapRef}>
            {/* Header Section */}
            <div className="bg-card-bg border-4 border-white p-8 shadow-[8px_8px_0px_0px_#FFD300] mb-8">
                <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 mb-6">
                    <div>
                        <h1 className="text-3xl font-black text-gray-900 dark:text-white mb-2">{learningPath.title}</h1>
                        <p className="text-gray-700 dark:text-gray-400 text-md">{learningPath.description}</p>
                    </div>
                    <button
                        onClick={onReset}
                        className="px-4 py-2 bg-gray-700 text-white font-bold border-2 border-white hover:bg-gray-600 transition-all whitespace-nowrap"
                    >
                        ↻ Create New
                    </button>
                </div>

                {/* Stats */}
                <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                    <div className="text-center">
                        <div className="text-3xl font-black text-accent-yellow">{learningPath.milestones.length}</div>
                        <div className="text-sm text-gray-400">Milestones</div>
                    </div>
                    <div className="text-center">
                        <div className="text-3xl font-black text-gray-900 dark:text-white">{learningPath.estimatedDuration}</div>
                        <div className="text-sm text-gray-400">Duration</div>
                    </div>
                    <div className="text-center">
                        <div className="text-3xl font-black text-accent-yellow">
                            {learningPath.milestones.reduce((sum, m) => sum + m.resources.length, 0)}
                        </div>
                        <div className="text-sm text-gray-400">Resources</div>
                    </div>
                </div>
            </div>

            {/* Timeline Visualization */}
            <div className="relative">
                {/* Vertical Line */}
                <div className="absolute left-8 top-0 bottom-0 w-1 bg-gradient-to-b from-accent-yellow via-accent-mint to-accent-blue hidden md:block" />

                {/* Milestones */}
                <div className="space-y-6">
                    {learningPath.milestones.map((milestone) => {
                        const isExpanded = expandedMilestone === milestone.id;

                        return (
                            <div key={milestone.id} className="relative">
                                {/* Timeline Node */}
                                <div className="hidden md:flex absolute left-0 top-6 items-center justify-center">
                                    <div className="w-16 h-16 border-4 border-white bg-card-bg text-gray-900 dark:text-white shadow-[4px_4px_0px_0px_#FFD300] flex items-center justify-center font-black text-xl transition-all">
                                        {milestone.id}
                                    </div>
                                </div>

                                {/* Milestone Card */}
                                <div className="md:ml-32">
                                    <MilestoneCard
                                        milestone={milestone}
                                        isExpanded={isExpanded}
                                        onToggle={() => toggleMilestone(milestone.id)}
                                    />
                                </div>
                            </div>
                        );
                    })}
                </div>
            </div>

            {/* Export Options */}
            <div data-html2canvas-ignore className="mt-8 flex flex-wrap gap-4 justify-center">
                <button
                    onClick={handleDownloadPDF}
                    disabled={isExporting}
                    className="px-6 py-3 bg-red-500 text-white font-bold border-3 border-white shadow-[4px_4px_0px_0px_#FFFFFF] hover:translate-y-1 hover:shadow-none transition-all disabled:opacity-50 disabled:cursor-not-allowed"
                >
                    {isExporting ? 'Generating...' : '📄 Download PDF'}
                </button>
            </div>
        </div>
    );
}
